import numpy as np

from proj1_helpers import load_csv_data, create_csv_submission
from helpers import standardize
from logistic_regression import *

def train(n_iters, gamma, precision):
    y, x, ids = load_csv_data('data/train.csv')
    tx = standardize(x)

    w = logistic_reg_gd(y, tx, np.zeros(tx.shape[1]), n_iters, gamma, precision)
    print(w)
    return w


def predict(w):
    """
    predict results are stored in res.csv
    """
    test_x = np.genfromtxt('data/test.csv', delimiter=',', skip_header=1)
    test_x = standardize(test_x[:, 2:])
    create_csv_submission([i for i in range(350000,918238)], log_reg_predict(test_x, w), 'res.csv')


w = train(2000, 0.000003, 1e-6)
# the following w is generated by running the statement above
# w = [ 0.9747362, 1.83745876, -4.7779175, -1.52974334, 2.27437374, -0.04872638, 0.71827331, -0.02647938, 0.27993284, -0.87375827, -0.18952824, 0.16329584, 0.40148036, -0.00543453, 2.81351968, 0.28852956, 0.28790223, -0.99564436, 0.28865406,  0.30209679, 0.31102132, 0.30721355, -1.6873265, 0.24447947, 0.09378955, 0.08747951, 0.08586542, -0.63493895, -0.01971049, -0.02707797, -1.4205089 ]
predict(w)
